//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koffeinfrei.Zueribad.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Koffeinfrei.Zueribad.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap baths {
            get {
                object obj = ResourceManager.GetObject("baths", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to defaults.
        /// </summary>
        internal static string ButtonReset {
            get {
                return ResourceManager.GetString("ButtonReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap choosecolor {
            get {
                object obj = ResourceManager.GetObject("choosecolor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha value must be between 0.0 and 1.0.
        /// </summary>
        internal static string ErrorAlpha {
            get {
                return ResourceManager.GetString("ErrorAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color code may only contain hex values ([0-9a-f]).
        /// </summary>
        internal static string ErrorHexCode {
            get {
                return ResourceManager.GetString("ErrorHexCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a valid number.
        /// </summary>
        internal static string ErrorNumber {
            get {
                return ResourceManager.GetString("ErrorNumber", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap homepage {
            get {
                object obj = ResourceManager.GetObject("homepage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min..
        /// </summary>
        internal static string LabelMinutesAbbreviation {
            get {
                return ResourceManager.GetString("LabelMinutesAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest update.
        /// </summary>
        internal static string LabelModified {
            get {
                return ResourceManager.GetString("LabelModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color.
        /// </summary>
        internal static string LabelSettingsBackColor {
            get {
                return ResourceManager.GetString("LabelSettingsBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite bath.
        /// </summary>
        internal static string LabelSettingsFavoriteBath {
            get {
                return ResourceManager.GetString("LabelSettingsFavoriteBath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font color.
        /// </summary>
        internal static string LabelSettingsFontColor {
            get {
                return ResourceManager.GetString("LabelSettingsFontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LabelSettingsLanguage {
            get {
                return ResourceManager.GetString("LabelSettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update interval.
        /// </summary>
        internal static string LabelSettingsUpdateInterval {
            get {
                return ResourceManager.GetString("LabelSettingsUpdateInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water temperature.
        /// </summary>
        internal static string LabelWaterTemperatur {
            get {
                return ResourceManager.GetString("LabelWaterTemperatur", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap loading1 {
            get {
                object obj = ResourceManager.GetObject("loading1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap loading2 {
            get {
                object obj = ResourceManager.GetObject("loading2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baths.
        /// </summary>
        internal static string MenuBaths {
            get {
                return ResourceManager.GetString("MenuBaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MenuQuit {
            get {
                return ResourceManager.GetString("MenuQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
